version: "3"

services:
  caddy:
    image: caddy:2.4.6
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8448:8448
      - 8080:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /mnt/disk/caddy/caddy_data:/data/caddy
      - /mnt/disk/nextcloud/nextcloud_data:/var/www/html