version: "3"

services:
  nextcloud_db:
    image: mariadb:10.5.6-focal
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /mnt/disk/nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=XXXX
      - MYSQL_PASSWORD=YYYY
      - MYSQL_DATABASE=nextclouddb
      - MYSQL_USER=nextclouduser

  nextcloud:
    image: nextcloud:20-fpm
    restart: always
    depends_on:
      - nextcloud_db
    volumes:
      - /mnt/disk/nextcloud_data:/var/www/html
      - ./www2.conf:/usr/local/etc/php-fpm.d/www2.conf

  synapse_db:
      image: postgres:13
      restart: always
      environment:
          POSTGRES_PASSWORD: mJ6bG2j8csXXxPsvDvub
          POSTGRES_USER: synapse
          POSTGRES_DB: synapse
          POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
      volumes:
          - "/mnt/disk/synapse_db:/var/lib/postgresql/"

  turn:
      image: "instrumentisto/coturn:4.5"
      restart: always
      volumes:
          - "/mnt/disk/coturn_data:/var/lib/coturn/"
          - "./coturn.conf:/etc/coturn/turnserver.conf"
          - "/mnt/disk/caddy_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/turn.domain.name:/etc/certs/"
      network_mode: host

  synapse:
      image: "matrixdotorg/synapse:v1.22.1"
      restart: always
      depends_on:
          - synapse_db
      volumes:
          - "/mnt/disk/synapse_data:/data"
      environment:
          SYNAPSE_SERVER_NAME: "matrix.domain.name"
          SYNAPSE_REPORT_STATS: "yes"
          TZ: "FR"

  synapse_admin:
      image: "awesometechnologies/synapse-admin:latest"
      restart: always
      depends_on:
          - synapse
          - turn

  caddy:
    image: caddy:2.1.1
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8448:8448
      - 8080:8080
    depends_on:
      - nextcloud
      - synapse_admin
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /mnt/disk/caddy_data:/data
      - /mnt/disk/nextcloud_data:/var/www/html