version: "3"

services:
  nextcloud_db:
    image: mariadb:10.5.6-focal
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /mnt/disk/nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=XXXX
      - MYSQL_PASSWORD=YYYY
      - MYSQL_DATABASE=nextclouddb
      - MYSQL_USER=nextclouduser

  nextcloud:
    build:
      context: .
      dockerfile: Dockerfile-nextcloud
    restart: always
    depends_on:
      - nextcloud_db
    volumes:
      - /mnt/disk/nextcloud_data:/var/www/html
      - ./www2.conf:/usr/local/etc/php-fpm.d/www2.conf

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    ports:
      - 8880:80
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=secret
   volumes:
      - /mnt/disk/only_office/document_data:/var/www/onlyoffice/Data
      - /mnt/disk/only_office/document_log:/var/log/onlyoffice
      - /mnt/disk/only_office/file_cache:/var/lib/onlyoffice
      - /mnt/disk/only_office/database:/var/lib/postgresql

  synapse_db:
      image: postgres:13
      restart: always
      environment:
          POSTGRES_PASSWORD: ZZZ
          POSTGRES_USER: synapse
          POSTGRES_DB: synapse
          POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
      volumes:
          - "/mnt/disk/synapse_db:/var/lib/postgresql/"
  
  synapse_db_backups:
    container_name: Backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - /mnt/disk/synapse_db_backups:/backups
    depends_on:
      - synapse_db
    environment:
      - POSTGRES_HOST=synapse_db
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=ZZZ
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - HEALTHCHECK_PORT=81

  turn:
      image: "instrumentisto/coturn:4.5"
      restart: always
      volumes:
          - "/mnt/disk/coturn_data:/var/lib/coturn/"
          - "./coturn.conf:/etc/coturn/turnserver.conf"
          - "/mnt/disk/caddy_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/turn.domain.name:/etc/certs/"
      network_mode: host

  synapse:
      image: "matrixdotorg/synapse:v1.32.2"
      restart: always
      depends_on:
          - synapse_db
      volumes:
          - "/mnt/disk/synapse_data:/data"
      environment:
          SYNAPSE_SERVER_NAME: "matrix.domain.name"
          SYNAPSE_REPORT_STATS: "yes"
          TZ: "FR"

  synapse_admin:
      image: "awesometechnologies/synapse-admin:0.7.2"
      restart: always
      depends_on:
          - synapse
          - turn

  caddy:
    image: caddy:2.4.3
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8448:8448
      - 8080:8080
    depends_on:
      - nextcloud
      - synapse_admin
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /mnt/disk/caddy_data:/data
      - /mnt/disk/nextcloud_data:/var/www/html